Add plan_id to the plan resource
franckverrot/terraform-provider-stripe pull request #18
Opened 2019-08-05 18:52 UTC by bradrydzewski

Stripe gives you the ability to set a custom plan_id.  This can be useful if you want your development and production environments to mirror eachother.  This way I can ensure the code I tested in development will not fail due to incorrect plan ids in production (since they are the same).

In terraform 12.x the `id` field is reserved. I look at other projects, and the convention seems to prefix the attribute with the resource name. I therefore used `plan_id` instead of `id`.

2019-08-15 16:25 UTC, franckverrot requested changes
I had to weigh in the pros and cons of this PR (which I love, thanks for submitting it.)

Adding `plan_id` requires everyone to add one, and will make terraform complain about the missing `plan_id` that Stripe autogenerates for you if you don’t provide one.  I would love to keep the optional aspect of it so here’s a proposal (lease tell me if it’s misguided 😅) : let’s add a configuration option, say `custom_plan_id` (boolean) at the provider level, and conditionally deal with `plan_id`s in the callbacks ?

I can write the PR based on this PR or I can let you do it, what do you think?

Sorry it took time to articulate what was bothering me a bit with this new behavior :-)

Thanks again, and please tell me what works best for you!

2019-08-15 22:34 UTC, andylayton commented
Hey @franckverrot I think the way this was implemented, plan_id is optional and will only take effect if it's provided.

The only difference I see in the output is that for those resources where it was provided, an additional parameter is also generated ('terraform show' below)

```
resource "stripe_plan" "month" {
    active         = true
    amount         = 4800
    billing_scheme = "per_unit"
    currency       = "usd"
    id             = "my_custom_plan_id"
    interval       = "month"
    interval_count = 1
    nickname       = "snip"
    plan_id        = "my_custom_plan_id"
    product        = "prod_Fd7ab1lqYgDOGM"
    usage_type     = "licensed"
}
```

versus

```
resource "stripe_plan" "quarterly" {
    active         = true
    amount         = 14400
    billing_scheme = "per_unit"
    currency       = "usd"
    id             = "plan_FabcVyiq9TKUc1"
    interval       = "month"
    interval_count = 3
    nickname       = "snip"
    product        = "prod_Fd7ab1lqYgDOGM"
    usage_type     = "licensed"
}
```

Other than that difference, though, it looks like the plan_id parameter is indeed optional.

2019-08-16 00:35 UTC, franckverrot commented
> I think the way this was implemented, plan_id is optional and will only take effect if it's provided.

If I’m not providing a `plan_id` when creating the new plan, and re-run plan/apply, Terraform will notice differences and mention an update in-place because the API will return a `plan_id` for the state to store, but the definition doesn’t mention it.  The only fix I found was to set `Computed: true,` on `plan_id`, and Terraform doesn’t complain anymore.

I think it’s fine to make it both computed and optional, I tried locally and it seems to be working.  WDYT?

2019-08-25 19:42 UTC, bradrydzewski commented
as an aside, I do not think the plan id can ever be updated.  So if terraform detects the plan has been updated it should be considered an error.

2019-08-30 12:39 UTC, franckverrot commented
Merged here e16bdb8, thanks again!

2019-08-30 12:39 UTC, closed without merging